version: "3"
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: base_backend
    environment: 
      NODE_ENV: development
    env_file: 
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
      - mongo
      - redis
    volumes:
      - ./public:/home/node/app/public
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: base_backend
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports: 
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"